#!/bin/zsh

if [ -z "$1" ]; then
  echo "Error: note \"title\""
  exit 1
fi

file_name=$(echo "$1" | tr ' ' '-')
formatted_file_name=$(date "+%Y-%m-%d")_${file_name}.md
cd "/Users/vvvetroff/Documents/notebook" || exit
touch "inbox/${formatted_file_name}"
nvim "inbox/${formatted_file_name}"
